Popup Window
audukehinde/portfolio pull request #19
Opened 2021-10-12 20:02 UTC by audukehinde

# In this project I implemented the popup window and it has the following features:
## When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
## When the user clicks (or taps) the close (X) button, the popup disappears
##  I also generated my project section with Javascript

2021-10-12 20:15 UTC, carlos-ssh requested changes
Hello Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![changesrequested](https://user-images.githubusercontent.com/22258274/137022861-427f8adb-6ca2-42e2-9e73-3ddeaf6f35a8.gif)



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-12 20:15 UTC, carlos-ssh commented on main.js
> +document.addEventListener('DOMContentLoaded', () => {
- Kindly enable JS linters(ESLint) in your pull request.

2021-10-12 20:15 UTC, carlos-ssh commented on main.js
> +document.addEventListener('DOMContentLoaded', () => {
- Assign a License to your project.

2021-10-12 20:15 UTC, carlos-ssh commented on main.js
> +  document.getElementById('full-name').value = getLocalStorageData.fullName;
Kindly fix this issue related to this line:
![Screen Shot 2021-10-12 at 15 11 25](https://user-images.githubusercontent.com/22258274/137022561-1eabdb4e-e9a4-401b-9fce-7c690026b9fd.png)

[Live version](https://raw.githack.com/audukehinde/portfolio/Dom-manipulation/index.html)

2021-10-12 20:50 UTC, audukehinde commented on main.js
> +  document.getElementById('full-name').value = getLocalStorageData.fullName;
Hello Carlos. Thanks for your kind review. I'm not getting this particular error at my end. How do I fix it? Thanks

2021-10-13 08:12 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Kenny Audu, 
 ### Thank you for working on the changes suggested previously. :ok_hand:

## To Improve 🙏
### But I am unable to see your project's Pop-up section. In fact, no project is showing. Kindly double-check everything is working fine before asking for a review.

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-13 11:24 UTC, dasileker approved these changes
### **Hi @audukehinde,** 

### **Congratulations! 🎉 Project Approved 💯✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 


![Approved](https://user-images.githubusercontent.com/61562626/137123430-572a2a1f-ac6f-40c2-b555-2c0d23b7bac3.gif)
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-13 15:44 UTC, merged